DOXYFILE = 'Doxyfile-mcss'

MAIN_PROJECT_URL = './index.html'
SHOW_UNDOCUMENTED = True

FINE_PRINT = """<p>scs-eigen docs. Licensed under the <a href="https://github.com/GiulioRomualdi/scs-eigen/blob/main/LICENSE">MIT License</a>. <br />Generated by <a href="https://doxygen.org/">Doxygen</a> {doxygen_version} and <a href="https://mcss.mosra.cz/">m.css</a>. Contact the team via <a href="https://github.com/GiulioRomualdi/scs-eigen">GitHub</a>"""


LINKS_NAVBAR1 = [
    ('Pages', 'pages', []),
    ('Classes', 'annotated', []),
    ('Files', 'files', [])
]
LINKS_NAVBAR2 = [
    ('<a href=\"https://github.com/GiulioRomualdi/scs-eigen\">GitHub</a>', [])
]
